### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by Jagermeister56** [pankaj9310/graviex-peatio#1]
i have RabbitMQ Running (no errors) :15672
i have nGinx running (no errors)
Test domain and port forwarding (no errors) :80 & 443
BitcoinD running
All Daemons Running
RAILS_ENV=production rake solvency:liability_proof (passes)
MySQL all tables & admin member

My problem is once i try to log in, i get an error from website
"We're sorry, but something went wrong."
no code, no reason

/home/deploy/peatio/current/log/production.log

I, [2018-06-21T12:21:17.945896 #13519]  INFO -- : Processing by WelcomeController#index as HTML
I, [2018-06-21T12:21:17.992619 #13519]  INFO -- : Completed 500 Internal Server Error in 46ms
F, [2018-06-21T12:21:17.995803 #13519] FATAL -- :
NoMethodError (undefined method `value' for nil:NilClass):
  app/models/member.rb:147:in `has_gio_deposite_50'
  app/models/account.rb:194:in `gio_discount'
  app/controllers/application_controller.rb:235:in `block in set_gon'
  app/controllers/application_controller.rb:230:in `set_gon'
  lib/middleware/security.rb:11:in `call'

E, [2018-06-21T12:24:45.273110 #3221] ERROR -- : Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' '2018-06$

**Comment by pankaj9310** [comment]
@Jagermeister56 
Add this  code in config/currencies.yml file
- id: 5
  key: gravio
  code: gio
  proto: GIO
  symbol: "G"
  coin: true
  quick_withdraw_max: 0
  rest: http://localhost
  rpc: http://username:password@127.0.0.1:18332
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: 1HjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3

**Comment by gjnardoni** [comment]
Hello. I've added the code, it now passes db:setup, however when I try to login (even as admin) i ran over that same error
