### ISSUE TITLE
in /funds , all other wallets dissapear after admin accept CNY DEPOSIT

### ISSUE THREAD

**Issue by openbooknoobdeveloper** [pankaj9310/graviex-peatio#11]
a funny case happened, after the admin accept the CNY deposit the wallets BTC and GIO dissapeared from funds.

in /funds , all other wallets dissapear after admin accept CNY DEPOSIT

![yen](https://user-images.githubusercontent.com/38215936/48547257-5522ce80-e8b1-11e8-8005-45229eb069df.jpg)

**Comment by pankaj9310** [comment]
@openbooknoobdeveloper you can see on top that is one option on and off coins

**Comment by pankaj9310** [comment]
@openbooknoobdeveloper resolved plz pull code
