### ISSUE TITLE
undefined method `base_secret'

### ISSUE THREAD

**Issue by joenilan** [pankaj9310/graviex-peatio#16]
`I, [2018-12-03T04:43:24.460287 #3978]  INFO -- : [error]: undefined method `base_secret' for #<Currency:0x0055a9a44d93d0>`

Could you tell me what this is tied to or have any info on what this is?

**Comment by pankaj9310** [comment]
@joenilan 
https://github.com/pankaj9310/graviex-peatio/blob/master/app/models/worker/withdraw_coin.rb
line number 58 plz replace below code and try again
`txid = CoinRPC[withdraw.currency].sendtoaddress withdraw.fund_uid, withdraw.amount.to_f`

**Comment by joenilan** [comment]
@pankaj9310 
ahhh, thank you, that was my next test!
this time
Result:
`I, [2018-12-03T06:38:23.689636 #6611]  INFO -- : [error]: wrong number of arguments (2 for 3)`


edit:
Is this referring to something in app/services/coin_rpc.rb ?

2nd Edit:
I also found this in the production.log
`E, [2018-12-04T00:58:29.186160 #5644] ERROR -- : undefined method 'home' for #<Currency:0x0055932b5f48f8>`
