### ISSUE TITLE
Wallets always offline

### ISSUE THREAD

**Issue by LightBurdenOfficial** [pankaj9310/graviex-peatio#19]
I did all the procedure to register new wallets in the system, but my wallets do not generate address and have OFFLINE status.

![image](https://user-images.githubusercontent.com/32315718/54800456-c1875300-4c40-11e9-9dfb-2db5bef5ce45.png)

**Comment by LightBurdenOfficial** [comment]
Logs:


HOT_WALLET:
> Processing coin = spero (?offline)
> [error]: undefined method `rest' for #<Currency:0x36e48f0>
> /home/spero/peatio/app/models/concerns/international.rb:10:in `method_missing'
> /home/spero/peatio/app/services/coin_rpc.rb:12:in `initialize'
> /home/spero/peatio/app/services/coin_rpc.rb:33:in `new'
> /home/spero/peatio/app/services/coin_rpc.rb:33:in `[]'
> /home/spero/peatio/app/models/currency.rb:39:in `api'
> /home/spero/peatio/app/models/currency.rb:91:in `refresh_balance'
> /home/spero/peatio/lib/daemons/hot_wallets.rb:21:in `block in <top (required)>'
> /home/spero/peatio/lib/daemons/hot_wallets.rb:18:in `each'
> /home/spero/peatio/lib/daemons/hot_wallets.rb:18:in `<top (required)>'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
> /home/spero/peatio/vendor/bundle/ruby/2.3.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
> lib/daemons/hot_wallets_ctl:6:in `<main>'

**Comment by LightBurdenOfficial** [comment]
I fixed the 'rest' error by adding the following:


![image](https://user-images.githubusercontent.com/32315718/55511454-0777ea00-5637-11e9-8bbe-c4c9f9483ac0.png)


But now I get this error ho file 'hot_wallet.rb.output':

![image](https://user-images.githubusercontent.com/32315718/55511507-2d04f380-5637-11e9-8dd9-53a23b4de2c3.png)

**Comment by openbooknoobdeveloper** [comment]
did u fix @DigitalCoin1 ?

**Comment by LightBurdenOfficial** [comment]
> did u fix @DigitalCoin1 ?

No...

**Comment by LightBurdenOfficial** [comment]
@openbooknoobdeveloper In the "currencies.yml" configuration modify the lines:
proto: BTC

Add the following information, if it is a currency based on the new BTC protocol, such as the LTC ...:
proto: BTC
family: BTC

![image](https://user-images.githubusercontent.com/32315718/56385067-6ec79980-61f4-11e9-8621-ee42b81986ff.png)


If the currency is the previous protocol, use:
proto: OLD_BTC
family: OLD_BTC

![image](https://user-images.githubusercontent.com/32315718/56385077-771fd480-61f4-11e9-8476-1777342d417e.png)


Using these settings I was able to connect all the wallets in my exchange.

![image](https://user-images.githubusercontent.com/32315718/56385150-b0584480-61f4-11e9-8f5c-e3c5814bfacc.png)
