### ISSUE TITLE
Never generates Addresses

### ISSUE THREAD

**Issue by Jagermeister56** [pankaj9310/graviex-peatio#3]
Everything runs great, 
All daemons are working 100%
Will not create bitcoin deposit address.
Bitcoind is working on other server (in LAN) 
able to NC to server IP and port with success

these are the lines i used to connect, perhaps this is the problem 

### in bitcoin.conf
rpcuser=complexusername
rpcpassword=complexpassword
rpcport=8332

rpcallowip=10.20.30.96

walletnotify=/usr/local/sbin/rabbitmqadmin --host=10.20.30.96 publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}'

### in currency.yml

rpc: http://complexusername:complexpassword@10.20.30.96:8332

Any advice would be extremely helpful. 

Thanks!

**Comment by Jagermeister56** [comment]
error in currencies_stats.rb.output 
Error: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' '2018-07-29 19:03:22', null, 1532916202)' at line 1: insert into currencies_summary (currency, locked, balance, hot, created_at, updated_at, slice) values ('CNY', 0.0, 0.0, , '2018-07-29 19:03:22', null, 1532916202)




error in production.log
E, [2018-07-29T19:03:23.020833 #1759] ERROR -- : Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' '2018-07-29 19:03:22', null, 1532916202)' at line 1: insert into currencies_summary (currency, locked, balance, hot, created_at, updated_at, slice) values ('CNY', 0.0, 0.0, , '2018-07-29 19:03:22', null, 1532916202)




error in hot_wallets.rb.log
lib/daemons/hot_wallets_ctl:6:in `<main>'
E, [2018-07-29T16:39:46.900994 #69310] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)

lib/daemons/hot_wallets_ctl:6:in `<main>'
E, [2018-07-29T16:39:46.980880 #69310] ERROR -- : no implicit conversion of nil into String (TypeError)



error in peatio:amqp:deposit_coin_address:1.log
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
E, [2018-07-29T16:39:47.577164 #69589] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)

**Comment by pankaj9310** [comment]
Please share currencies.yml file

**Comment by Jagermeister56** [comment]
- id: 1
  key: renminbi
  code: cny
  symbol: "¥"
  coin: false
  precision: 2
  assets:
    accounts:
      -
        bank: '招商银行'
        address: '6225 0885 6022 3501'
        password: '111111'
        tel: '95555'
- id: 2
  key: satoshi
  code: btc
  symbol: "฿"
  coin: true
  quick_withdraw_max: 0
  rpc: http://COMPLEXUSERNAME:COMPLEXPASSWORD@10.20.30.87:8332
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: 1JTBFm2PmpgGZMFGwmdHnY5wBndBgWAoKF
- id: 3
  key: gravio
  code: gio
  proto: GIO
  symbol: "G"
  coin: true
  quick_withdraw_max: 0
  rest: http://localhost
  rpc: http://username:password@127.0.0.1:18332
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: 1HjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3

**Comment by Jagermeister56** [comment]
Bitcoin Daemon running on other server IP (.87)
Peatio Running on Main Server (.96)

**Comment by laugh26** [comment]
when i run this bundle exec rails server, i get ERROR bad URI `�=)�-\x00\x00\x1C�������+�/�,�0�\x13�\x14\x00�\x00�\x00/\x005\x00

**Comment by pankaj9310** [comment]
@laugh26 Plz post log file

**Comment by laugh26** [comment]
whenever i start with bundle exec rails server , it tell me 
=> Booting WEBrick
=> Rails 4.0.12 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2018-08-24 13:21:04] INFO  WEBrick 1.3.1
[2018-08-24 13:21:04] INFO  ruby 2.2.1 (2015-02-26) [x86_64-linux]
[2018-08-24 13:21:04] INFO  WEBrick::HTTPServer#start: pid=59638 port=3000
 
when i check on web browser i get 
[2018-08-24 13:24:59] ERROR bad Request-Line `\x16\x03\x01\x00�\x01\x00\x00�\x03\x03\x14���\a����A\x00\v�\x02_^X\x1F'\x01%�i\\�\r��\x12�\x1C\x05\x00\x00\x1C�������+�/�,�0�\x13�\x14\x00�\x00�\x00/\x005\x00'.
[2018-08-24 13:24:59] ERROR bad URI `c#��\x00\x00\x1C�������+�/�,�0�\x13�\x14\x00�\x00�\x00/\x005\x00'.
on the console and the webpage does not open

**Comment by pankaj9310** [comment]
Hi 
1) stop rails server
2) rake tmp:clear
then start server again

**Comment by laugh26** [comment]
Thanks @pankaj9310  for your solution but it was not the problem, the problem was because of ssl and nginx not properly configured. Thanks for your work.

**Comment by AnthonyRex** [comment]
> Thanks @pankaj9310 for your solution but it was not the problem, the problem was because of ssl and nginx not properly configured. Thanks for your work.

how did you manage to get the address generated ? I have everything else working . it's offline and no address. , I am trying for 2 days now with no success.  managed by Certbot.  
here are some errors from my production log

I, [2018-10-25T22:42:06.853103 #4100]  INFO -- : Processing by Private::FundsController#index as HTML
E, [2018-10-25T22:42:06.895312 #4100] ERROR -- : undefined method `home' for #<Currency:0x005582b7d18780>
E, [2018-10-25T22:42:06.908212 #4100] ERROR -- : undefined method `home' for #<Currency:0x005582b7d17290>
E, [2018-10-25T22:42:06.919266 #4100] ERROR -- : undefined method `home' for #<Currency:0x005582b7d15e18>

![2018-10-26 2](https://user-images.githubusercontent.com/43102294/47534976-fb4f6a00-d8eb-11e8-8435-24233a6d9125.png)
-----------------------------------------

this is when i click on dividends link 

I, [2018-10-25T22:50:51.762028 #4100]  INFO -- : Started GET "/dividends" for 175.136.62.121 at 2018-10-25 22:50:51 +0000
I, [2018-10-25T22:50:51.780920 #4100]  INFO -- : Processing by Private::DividendsController#index as HTML
I, [2018-10-25T22:50:51.835090 #4100]  INFO -- : Completed 500 Internal Server Error in 54ms
F, [2018-10-25T22:50:51.836904 #4100] FATAL -- :
NoMethodError (undefined method `product' for nil:NilClass):
  app/controllers/private/dividends_controller.rb:9:in `index'
  lib/middleware/security.rb:11:in `call'

I would appreciate any help

**Comment by pblab-dev** [comment]
It's hard to find information, I suggest you see this https://bitcointalk.org/index.php?topic=5202005.new#new
